### ISSUE TITLE
Could I change the shortcut?

### ISSUE THREAD

**Issue by yllgl** [lutz/JumpToLastPositionAfterActionExecutionAddon#6]
My laptop is not convenient to press F3. If I want to press F3, I have to hold down the Fn key before I can press F3. so I have to hold down all three keys Alt+Fn+F3 at the same time to trigger it. can you please change the F3 key to a non-functional key?

**Comment by lutz** [comment]
@yllgl Currently i have not the time to change this behaviour. The Problem is that i must research which shortcut is free in Citavi. If you have the possibility feel free to fork the project an recompile it with another shortcut.

Or you can check if you have the possibility to switch the behaviour for your keyboard that the F* keys are activated and and for the "special" functions you must press the FN key. (On my laptop i had the same problem and could switch it)

**Comment by yllgl** [comment]
thank you very much! your advice is helpful and solved my problem!
